sudo: required
language: cpp
compiler: 
  - g++-4.8
before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
# We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - wget www.airspayce.com/mikem/bcm2835/bcm2835-1.42.tar.gz
  - tar xvfz bcm2835-1.42.tar.gz
  - cd bcm2835*
  - ./configure
  - make
  - sudo make install
  - cd ..
  - cd raspi/localization/wireless_tools.29
  - make
  - sudo make install
  - cd ../
  - g++ --version
script:  make

